### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [math-io/float32-to-word#1]
Note: atm, we cannot provide any type annotations (e.g., `x|0`) to prevent the compiler from doing implicit promotion of the returned value to a double-precision floating-point `number`. All bitwise operators return signed 32-bit `integers`. Once typed objects land, we may have more control over the type of what gets returned.

**Comment by Planeshifter** [comment]
So there is no way to return an unsigned integer. Bummer. I looked through the code and couldn't spot any problems. Publish?

**Comment by kgryte** [comment]
We have no way to "guarantee" in userland atm an `unsigned integer`. We rely on compilers to not perform type promotion once a value is accessed from an `unsigned integer` buffer. 

Thanks for reviewing!
